services:
    final-hour:
        build:
            context: .
            target: final-hour-dev
        restart: unless-stopped
        environment:
            - FH_NO_DISCORD=1
        volumes:
            - ./:/home/node/app
        ports:
            - 13000:13000/udp
